# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 406)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color:rgb(184,184,184);\n"
"border-radius:10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_NationalCode = QtWidgets.QLabel(parent=self.frame)
        self.label_NationalCode.setObjectName("label_NationalCode")
        self.verticalLayout_3.addWidget(self.label_NationalCode)
        self.lineEdit_NationalCode = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_NationalCode.setStyleSheet("background-color:rgb(255,255,255);\n"
"padding:3px;")
        self.lineEdit_NationalCode.setObjectName("lineEdit_NationalCode")
        self.verticalLayout_3.addWidget(self.lineEdit_NationalCode)
        self.label_ISBN = QtWidgets.QLabel(parent=self.frame)
        self.label_ISBN.setObjectName("label_ISBN")
        self.verticalLayout_3.addWidget(self.label_ISBN)
        self.lineEdit_ISBN = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_ISBN.setStyleSheet("background-color:rgb(255,255,255);\n"
"padding:3px;")
        self.lineEdit_ISBN.setObjectName("lineEdit_ISBN")
        self.verticalLayout_3.addWidget(self.lineEdit_ISBN)
        self.label_DateDeliveryToPerson = QtWidgets.QLabel(parent=self.frame)
        self.label_DateDeliveryToPerson.setObjectName("label_DateDeliveryToPerson")
        self.verticalLayout_3.addWidget(self.label_DateDeliveryToPerson)
        self.lineEdit_DateDeliveryToPerson = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_DateDeliveryToPerson.setStyleSheet("background-color:rgb(255,255,255);\n"
"padding:3px;")
        self.lineEdit_DateDeliveryToPerson.setObjectName("lineEdit_DateDeliveryToPerson")
        self.verticalLayout_3.addWidget(self.lineEdit_DateDeliveryToPerson)
        self.label_DateDeliveryFromPerson = QtWidgets.QLabel(parent=self.frame)
        self.label_DateDeliveryFromPerson.setObjectName("label_DateDeliveryFromPerson")
        self.verticalLayout_3.addWidget(self.label_DateDeliveryFromPerson)
        self.lineEdit_DateDeliveryFromPerson = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_DateDeliveryFromPerson.setStyleSheet("background-color:rgb(255,255,255);\n"
"padding:3px;")
        self.lineEdit_DateDeliveryFromPerson.setObjectName("lineEdit_DateDeliveryFromPerson")
        self.verticalLayout_3.addWidget(self.lineEdit_DateDeliveryFromPerson)
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.pushButton_done = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_done.setStyleSheet("")
        self.pushButton_done.setObjectName("pushButton_done")
        self.verticalLayout_2.addWidget(self.pushButton_done)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignTop)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "add depositts"))
        self.label_NationalCode.setText(_translate("Dialog", "National Code:"))
        self.label_ISBN.setText(_translate("Dialog", "ISBN:"))
        self.label_DateDeliveryToPerson.setText(_translate("Dialog", "Date Delivery To Person:"))
        self.label_DateDeliveryFromPerson.setText(_translate("Dialog", "Date Delivery From Person:"))
        self.pushButton_done.setText(_translate("Dialog", "DONE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
