# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class AddBookUi(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(491, 527)
        Dialog.setStyleSheet("background-color:#8d99ae;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setStyleSheet("background-color:#2b2d42;\n"
"border-radius:10px;")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.widget)
        self.frame_2.setStyleSheet("background-color:#8d99ae;\n"
"border-radius:10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
"padding-left:5px;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setStyleSheet("background-color:rgb(255,255,255);\n"
"padding:3px;")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout_2.addWidget(self.lineEdit_name)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
"padding-left:5px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_Author = QtWidgets.QLineEdit(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_Author.setFont(font)
        self.lineEdit_Author.setStyleSheet("background-color:rgb(255,255,255);\n"
"padding:3px;")
        self.lineEdit_Author.setObjectName("lineEdit_Author")
        self.verticalLayout_2.addWidget(self.lineEdit_Author)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"padding-left:5px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.lineEdit__ISBN = QtWidgets.QLineEdit(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit__ISBN.setFont(font)
        self.lineEdit__ISBN.setStyleSheet("background-color:rgb(255,255,255);\n"
"padding:3px;")
        self.lineEdit__ISBN.setObjectName("lineEdit__ISBN")
        self.verticalLayout_2.addWidget(self.lineEdit__ISBN)
        self.label_ = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_.setFont(font)
        self.label_.setStyleSheet("color:white;\n"
"padding-left:5px;")
        self.label_.setObjectName("label_")
        self.verticalLayout_2.addWidget(self.label_)
        self.lineEdit_Translator = QtWidgets.QLineEdit(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_Translator.setFont(font)
        self.lineEdit_Translator.setStyleSheet("background-color:rgb(255,255,255);\n"
"padding:3px;")
        self.lineEdit_Translator.setObjectName("lineEdit_Translator")
        self.verticalLayout_2.addWidget(self.lineEdit_Translator)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;\n"
"padding-left:5px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_Publicatipn = QtWidgets.QLineEdit(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_Publicatipn.setFont(font)
        self.lineEdit_Publicatipn.setStyleSheet("background-color:rgb(255,255,255);\n"
"padding:3px;")
        self.lineEdit_Publicatipn.setObjectName("lineEdit_Publicatipn")
        self.verticalLayout_2.addWidget(self.lineEdit_Publicatipn)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;\n"
"padding-left:5px;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.lineEdit_NumberOfPages = QtWidgets.QLineEdit(parent=self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_NumberOfPages.setFont(font)
        self.lineEdit_NumberOfPages.setStyleSheet("background-color:rgb(255,255,255);\n"
"padding:3px;")
        self.lineEdit_NumberOfPages.setText("")
        self.lineEdit_NumberOfPages.setObjectName("lineEdit_NumberOfPages")
        self.verticalLayout_2.addWidget(self.lineEdit_NumberOfPages)
        self.label_Alert = QtWidgets.QLabel(parent=self.frame_2)
        self.label_Alert.setStyleSheet("color:rgb(204, 16, 16);\n"
"margin-left:3px")
        self.label_Alert.setText("")
        self.label_Alert.setObjectName("label_Alert")
        self.verticalLayout_2.addWidget(self.label_Alert)
        self.verticalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.pushButton_done = QtWidgets.QPushButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_done.setFont(font)
        self.pushButton_done.setStyleSheet("background-color:#2b2d42;\n"
"border-radius:6px;\n"
"color:white\n"
"")
        self.pushButton_done.setObjectName("pushButton_done")
        self.verticalLayout.addWidget(self.pushButton_done)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "name:"))
        self.label_2.setText(_translate("Dialog", "Author"))
        self.label_4.setText(_translate("Dialog", "ISBN"))
        self.label_.setText(_translate("Dialog", "Translator:"))
        self.label_3.setText(_translate("Dialog", "Publication:"))
        self.label_6.setText(_translate("Dialog", "NumberOfPages:"))
        self.pushButton_done.setText(_translate("Dialog", "D O N E !"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
